# Site settings
title: Allen Akinkunle | Data Science, Machine Learning
content: Data Science, Machine Learning, Data Visualisation, Software Development
description: "The personal website of Allen Akinkunle"
url: "http://www.allenkunle.me"
author:
  name: "Allen Akinkunle"
  email: "hello@allenkunle.me"
  url: "http://www.allenkunle.me"
  twitter: "@allenakinkunle"

# Gems
plugins:     [jekyll-paginate]

# Tag page
tag_page_layout: tag
tag_page_dir: tags

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/
url: http://allenkunle.me

# Syntax Highlighter
kramdown:
  input: GFM
  syntax_highlighter: rouge


# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.0"

# Options
reverse: true

timezone: Europe/London

exclude: [Gemfile, Rakefile, Gemfile.lock]

sass:
  style: compressed
